### ISSUE TITLE
Календарь для разных моделей

### ISSUE THREAD

**Issue by loveorigami** [Understeam/yii2-calendar-widget#1]
Прочитал, как установить виджет. 
Как я понял - он работает  с одной моделью, которую приписываешь в настройках компонента.

Допустим, мне надо отобразить календарную сетку новостей, или постов.
Например, как здесь
http://new.loveorigami.info/loveis/year/2004 - выводятся все записи из модели `loveis` за год с днями-ссылками, где имеются записи.
Аналогично хочу сделать и для новостей, и постов и т.д.

Или специфика вашего виджета немного другая?

**Comment by AnatolyRugalev** [comment]
@loveorigami, виджет предназначен для вывода в режимах просмотра "Неделя" или "Месяц". "Год" не был реализован, но, в целом, его можно добавить. Я разрабатывал его под нужды определённого проекта.
Внешний вид примерно такой: 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1397674/17324341/840a0634-58bf-11e6-90d1-d288f2a25bb1.gif)

Всплывающее окно в виджете отсутствует
